LOW_RISK_THRESHOLD = 0.40
HIGH_RISK_THRESHOLD = 0.70

def calculate_risk_level(probability: float) -> str:
    if probability < LOW_RISK_THRESHOLD:
        return "Low"
    elif probability < HIGH_RISK_THRESHOLD:
        return "Moderate"
    else:
        return "High"

DISCLAIMER = (
    "This result is generated by a machine learning model for academic and informational purposes only. "
    "It is not a medical diagnosis or clinical evaluation. "
    "Consult a qualified healthcare professional for medical advice."
)
